import { routing } from "@/i18n/routing";
import type { Metadata, Viewport } from "next";
import { hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import Navbar from "../components/Navbar/Navbar";
import MobileTabBar from "../components/Navbar/TabBar";
import { ThemeProvider } from "../components/providers/theme-provider";
import { quicksand } from "../fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const viewport: Viewport = {
  themeColor: "#4F46E5",
};
export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang="en">
      <body className={` ${quicksand.className}`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Navbar />
          <MobileTabBar />
        </ThemeProvider>
      </body>
    </html>
  );
}
